Parameters:
  ExportComputeStackName:
    Description: The name of the stack that exports the values
    Type: String
    Default: Compute-Stack-Dev  
  PMServerEnv:
    Description: "Server Environment name."
    ConstraintDescription: "Choose an Environment from the drop down"
    Type: "String"
  
    

Resources:
  WebServerScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Fn::ImportValue: !Sub '${ExportComputeStackName}-${PMServerEnv}-WEBAsg'
      Cooldown: '30'
      ScalingAdjustment: 1
  WebServerScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: 
        Fn::ImportValue: !Sub '${ExportComputeStackName}-${PMServerEnv}-WEBAsg'
      Cooldown: '30'
      ScalingAdjustment: -1
  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-up if CPU > 70% for 1 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 30
      EvaluationPeriods: 1
      Threshold: 70
      AlarmActions: [!Ref 'WebServerScaleUpPolicy']
      Dimensions:
      - Name: AutoScalingGroupName
        Value: 
          Fn::ImportValue: !Sub '${ExportComputeStackName}-${PMServerEnv}-WEBAsg'
      ComparisonOperator: GreaterThanThreshold
  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-down if CPU < 30% for 1 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 30
      EvaluationPeriods: 1
      Threshold: 30
      AlarmActions: [!Ref 'WebServerScaleDownPolicy']
      Dimensions:
      - Name: AutoScalingGroupName
        Value: 
          Fn::ImportValue: !Sub '${ExportComputeStackName}-${PMServerEnv}-WEBAsg'
      ComparisonOperator: LessThanThreshold
