# jobs:
#   - script: >
#       job('Job_DSL_Seed') {
#         scm {
#           git {
#             remote {
#               url 'https://github.com/shadabshah1680/jcasc.git'
#             }
#           }
#         }
#         steps {
#           jobDsl {
#             targets 'jobs/*.groovy'
#           }
#         }
#       }

jobs:
    - script: >
        pipelineJob("dev pipelines") {
        definition {
          def signature = 'new groovy.json.JsonSlurperClassic'
          org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.get().approveSignature(signature)
            cpsScm {
                scm {
                    git{
                      remote {
                        url("https://github.com/shadabshah1680/jcasc_1.git")
                      }
                      branch("*/main")
                    }
                }
            }
          }
        }    