jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'https://github.com/shadabshah1680/jcasc.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'jobs/*.groovy'
          }
        }
      }

    